import Head from "next/head";
import { Inter } from "next/font/google";
import styles_home from "@/styles/Home.module.css";
import styles_about from "@/styles/About.module.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>About</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles_home.main} ${inter.className}`}>
				{Navbar()}
				<h2 className={styles_about.titleMain}>Mon parcours</h2>
				<div className={styles_about.elementMainParcours}>
					<div className={styles_about.elementParcours}>
						<h3 className={styles_about.titleParcours}>2022</h3>
						<p className={styles_about.textParcours}>Baccaulauréat optenu avec mention bien et mention Européenne</p>
						<p className={styles_about.textParcours}>Inscription à l'école ISITECH pour un Bachelor Reponsable de Projets Informatiques</p>
						<p className={styles_about.textParcours}>Embauché chez M2M Financement pour une durée de 2 ans en tant que Développeur web PHP</p>
					</div>
					<div className={styles_about.elementParcours}>
						<h3 className={styles_about.titleParcours}>2019</h3>
						<p className={styles_about.textParcours}>Stage d'une semaine chez IMDEO</p>
						<p className={styles_about.textParcours}>Brevet des collèges optenu avec mention très bien</p>
					</div>
				</div>
			</main>
		</>
	);
}
