import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles_home from "@/styles/Home.module.css";
import styles_contact from "@/styles/Contact.module.css";
import Bonjour from "@/components/composant1";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Contact</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles_home.main} ${inter.className}`}>
				{Navbar()}
				<div className={styles_contact.mainElement}>
					<h2 className={styles_contact.titleMain}>Contact</h2>
					<form className={styles_contact.elementForm}>
						<div>
							<label htmlFor="name" className={styles_contact.label}>
								Nom
							</label>
							<input type="text" name="name" id="name" className={styles_contact.input} />
						</div>
						<div>
							<label htmlFor="email" className={styles_contact.label}>
								Email
							</label>
							<input type="email" name="email" id="email" className={styles_contact.input} />
						</div>
						<div>
							<label htmlFor="message" className={styles_contact.label}>
								Message
							</label>
							<textarea name="message" id="message" className={styles_contact.textarea}></textarea>
						</div>
						<button type="submit" className={styles_contact.btnPrimary}>
							Envoyer
						</button>
					</form>
				</div>
			</main>
		</>
	);
}
