import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Bonjour from "@/components/composant1";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Portfolio React</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				{Navbar()}
				<div className={styles.mainElement}>
					<div className={styles.elementTitle}>
						<p className={styles.titleMainElement}>Hey !</p>
						<p className={styles.titleMainElement}>
							I'm <span className={styles.elementBlue}>Clément</span>
						</p>
						<p className={styles.titleMainElement}>Web developper</p>
					</div>
					<img src="/img-clement.jfif" alt="Clément image" className={styles.clementImage} />
				</div>
				<button type="button" name="contact" value='contact' className={styles.btnPrimary}>Contact</button>
			</main>
		</>
	);
}
